import Admin from './Admin/Admin';
import AdminDashboard from './Admin/AdminDashboard';
import AppliedDoctors from './Admin/Doctors';
import AppliedHospital from './Admin/Hospitals';
import Users from './Admin/Users';
import ApplyDoctor from './doctor/ApplyDoctor';
import Doctor from './doctor/Doctor';
import Doctors from './doctor/Doctors';
import ForgetPassword from './ForgetPassword';
import Home from './Home';
import HospitalDetails from './HospitalDetails';
import Hospitals from './Hospitals';
import Layout from './Layout';
import NotFound from './NotFound';
import Notification from './Notification';
import Payments from './Payments';
import Profile from './Profile';
import ProtectedRoute from './ProtectedRoute';
import ResetPassword from './ResetPassword';
import Signin from './Signin';
import Signup from './Signup';
import VerifyAccount from './VerifyAccount';
import Appointment from './appointment/Appointment';
import AppointmentFind from './appointment/AppointmentFind';
import AppointmentSubmit from './appointment/AppointmentSubmit';
import Appointments from './appointment/Appointments';
import AppointmentsAllPatient from './appointment/AppointmentsAllPatient';
import AppointmentsAllPatientSearch from './appointment/AppointmentsAllPatientSearch';
import AddBalance from './payment/AddBalance';
import Failure from './payment/Failure';
import Success from './payment/Success';

export { AddBalance, Admin, AdminDashboard, AppliedDoctors, AppliedHospital, ApplyDoctor, Appointment, AppointmentFind, AppointmentSubmit, Appointments, AppointmentsAllPatient, AppointmentsAllPatientSearch, Doctor, Doctors, Failure, ForgetPassword, Home, HospitalDetails, Hospitals, Layout, NotFound, Notification, Payments, Profile, ProtectedRoute, ResetPassword, Signin, Signup, Success, Users, VerifyAccount };

