import AppoinmentChamberList from "./AppoinmentChamberList";
import AppointmentDetails from "./AppointmentDeatils";
import Delete from "./Delete";
import Doctor from "./Doctor";
import Head from "./Head";
import Header from "./Header";
import Heading from "./Heading";
import HowtoAddBalance from "./HowtoAddBalance";
import Info from "./Info";
import Input from "./Input";
import Loading from "./Loading";
import NoBalanceAlert from "./NoBalanceAlert";
import PrintHeader from "./PrintHeader";
import Upload from "./Upload";
import AppointmentsCardView from "./appointments/AppointmentsCardView";
import AppointmentsTableView from "./appointments/AppointmentsTableView";
import AddChamber from "./chamber/AddChamber";
import ChamberList from "./chamber/ChamberList";
import UpdateChamber from "./chamber/UpdateChamber";
import DoctorDetails from "./details/DoctorDetails";
import UserDetails from "./details/UserDetails";
import AddHospital from "./hospital/AddHospital";
import Hospital from "./hospital/Hospital";
import UpdateHospital from "./hospital/UpdateHospital";
import AddSpecialist from "./specialist/AddSpecialist";
import UpdateSpecialist from "./specialist/UpdateSpecialist";

export { AddChamber, AddHospital, AddSpecialist, AppoinmentChamberList, AppointmentDetails, AppointmentsCardView, AppointmentsTableView, ChamberList, Delete, Doctor, DoctorDetails, Head, Header, Heading, Hospital, HowtoAddBalance, Info, Input, Loading, NoBalanceAlert, PrintHeader, UpdateChamber, UpdateHospital, UpdateSpecialist, Upload, UserDetails };